[{'assessment_number': '1',
  'due_string': 'Multiple Weeks',
  'is_group': 'No',
  'name': 'Participation in practical programming tasks',
  'weight': '10.00'},
 {'assessment_number': '2',
  'due_string': 'Multiple Weeks',
  'is_group': 'No',
  'name': 'Quiz',
  'weight': '20.00'},
 {'assessment_number': '3',
  'due_string': 'Multiple Weeks',
  'is_group': 'No',
  'name': 'Lab Skills',
  'weight': '10.00'},
 {'assessment_number': '4',
  'due_string': 'Exam Period',
  'is_group': 'No',
  'name': 'Final Exam',
  'weight': '60.00'}]
